// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaadR_lpr61GQv2ebT6jzge4C1em00tTk',
    appId: '1:317600066104:web:3e2c15f5d844ee7fe914cd',
    messagingSenderId: '317600066104',
    projectId: 'tva-music-vault',
    authDomain: 'tva-music-vault.firebaseapp.com',
    storageBucket: 'tva-music-vault.appspot.com',
    measurementId: 'G-N2Q25ZCQ9Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4EqfE00CWey8hH1HUem8f9qCp2VdxAqU',
    appId: '1:317600066104:android:be66649f696e35dfe914cd',
    messagingSenderId: '317600066104',
    projectId: 'tva-music-vault',
    storageBucket: 'tva-music-vault.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvIIVtciinyZJa4kl1bMaysCJfCi2fI88',
    appId: '1:317600066104:ios:2e85759a0665a5bfe914cd',
    messagingSenderId: '317600066104',
    projectId: 'tva-music-vault',
    storageBucket: 'tva-music-vault.appspot.com',
    iosBundleId: 'com.example.musicVault',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvIIVtciinyZJa4kl1bMaysCJfCi2fI88',
    appId: '1:317600066104:ios:2e85759a0665a5bfe914cd',
    messagingSenderId: '317600066104',
    projectId: 'tva-music-vault',
    storageBucket: 'tva-music-vault.appspot.com',
    iosBundleId: 'com.example.musicVault',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCaadR_lpr61GQv2ebT6jzge4C1em00tTk',
    appId: '1:317600066104:web:724aa4b5f72c7080e914cd',
    messagingSenderId: '317600066104',
    projectId: 'tva-music-vault',
    authDomain: 'tva-music-vault.firebaseapp.com',
    storageBucket: 'tva-music-vault.appspot.com',
    measurementId: 'G-04SGFDCP7X',
  );
}
